apiVersion: v1
kind: Service
metadata:
  name: ctmag
spec:
  clusterIP: None # headless service
  selector:
    type: stateful-service-ctmag-srv
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.controlM.agent.agport }}
