apiVersion: batch/v1
kind: Job
metadata:
  name: c360srv03-job
spec:
  template:
    metadata:
      name: c360srv03
    spec:
      containers:
      - name: c360srv03
        image: joegoldberg/controlm:appimage
        imagePullPolicy: Always
        env:
        - name: LOOPCTR
          value: "10"
        - name: STIME
          value: "5"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
