apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlm-agent
  namespace: default
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---
# You need to use that account for your controlm-agent DaemonSet
kind: ServiceAccount
apiVersion: v1
metadata:
  name: controlm-agent
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controlm-agent
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: controlm-agent
subjects:
- kind: ServiceAccount
  name: controlm-agent
  namespace: default