apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostname: {{ .Release.Name }}
      {{ if .Values.image.deploysecret }}
      imagePullSecrets:
          - name: {{ .Values.image.deploysecret }}{{ end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/ctms
          ports:
          - name: agent-to-server
            containerPort: {{ .Values.ctm.AgentToServerPort }}
            protocol: TCP
          - name: config-agent
            containerPort: {{ .Values.ctm.ConfigurationAgentPort }}
            protocol: TCP
          - name: control-m-em
            containerPort: {{ .Values.ctm.ControlMEMTcpIpPort }}
            protocol: TCP
          env:
          - name: CTM_USER
            value: {{ .Values.ctm.aapi_user }}
          - name: CTM_SERVER
            value: {{ .Values.ctm.datacenter }}
          - name: CTM_HOST
            value: {{ .Values.ctm.aapi_endpoint }}
          - name: IMAGE
            value: {{ .Values.ctm.povisionImage }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE
            value: {{ .Release.Name }}{{ if .Values.install_debug }}
          - name: INSTALL_DEBUG
            value: "{{ .Values.install_debug }}"{{ end }}
          - name: NAME
            value: {{ .Chart.Name }}
          - name: CTM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ctm.aapi_passwd_secret_name }}
                key: {{ .Values.ctm.aapi_passwd_secret_key }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
