apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ctm.AgentToServerPort }}
      targetPort: {{ .Values.ctm.AgentToServerPort }}
      protocol: TCP
      name: agent-to-server
    - port: {{ .Values.ctm.ConfigurationAgentPort }}
      targetPort: {{ .Values.ctm.ConfigurationAgentPort }}
      protocol: TCP
      name: confg-agent
    - port: {{ .Values.ctm.ControlMEMTcpIpPort }}
      targetPort: {{ .Values.ctm.ControlMEMTcpIpPort }}
      protocol: TCP
      name: control-m-em
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
