UNLOAD ('SELECT * FROM <YOUR_SAGE_TABLE>')
TO 's3://<YOUR_S3_BUCKET>/<YOUR_S3_FOLDER>/Payments_RS.csv'
IAM_ROLE 'arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_REDSHIFT_ROLE>'
FORMAT AS csv
HEADER
ALLOWOVERWRITE
PARALLEL OFF
DELIMITER ','
MAXFILESIZE 6GB;  -- 1GB max per file
